apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName}}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.appName}}
  ports:
  - port: {{ .Values.servicePort }}
    targetPort: {{ .Values.appPort }}